### ISSUE TITLE
dropDownList load presets 

### ISSUE THREAD

**Issue by joaodafonseca** [rezaali/ofxUI#231]
Hi everybody, 

I'm not able to load any settings to the dropdownlist. I can save the .xml file and it seems ok, but then the loadSettings(".xml") function doesn't load any content to the dropdownlist.

Am I missing something?
thanks.

**Comment by rezaali** [comment]
fixed in the most recent commit: https://github.com/rezaali/ofxUI/commit/74228ec1fba2b90dbbf2f512e522327b4e866124

Thanks for finding this!
