### ISSUE TITLE
suggestion: possibility to change values of an ofxUILabel ~ use it as an variable inspector

### ISSUE THREAD

**Issue by dimitre** [rezaali/ofxUI#240]
Something like this:
```c++
guiMap["0"]->addLabel("dirName", &dirName); 
```
Where I can display variables, in this case the actual working directory.

This code runs without error but doesn't change label
```c++
ofxUILabel *l = (ofxUILabel*)guiMap["0"]->getWidget("dirName");
l->setLabel(dirName);
```
Thanks

**Comment by rezaali** [comment]
great idea! Will be updating ofxUI next month when I get some time! In the
mean time feel free to send me a pull request.

**Comment by rezaali** [comment]
@dimitre can you try this again and let me know if its still broken?

**Comment by dimitre** [comment]
@rezaali I'll be testing in a minute. I've noticed ofxUI is using some 0.9 specific commands like ofDrawLine ofDrawRectangle.
Thanks
