### ISSUE TITLE
iOS labels (Font ?) problem

### ISSUE THREAD

**Issue by martialgallorini** [rezaali/ofxUI#244]
Hello,

Fist off, thanks a lot for this impressive addon !

I used ofxUI for some projects on the desktop (mac)

now i am digging into iOS where i am totally newbie ! 

I tried examples and even a really simple stupid app i made (just one canvas and a label). Those are working except i can't see any labels (label, buttons, sliders...)

I used to have similar problems on the desktop that was due to either : 

- button / canvas not large enough to embed the labels
- no font to render (needed to copy /bin/data/GUI into the project)

I think this one seems related to font not being found ? I haven't used ofxUI addon for some time, but was there no Helvetica font to put into bin/data/GUI in previous versions (i can't find it in the examples) ?

I tried to copy /bin/data/gui to the iOS device but still no luck (am i copying it to the right place ?)

am i missing something ?

thanks for your help

**Comment by rezaali** [comment]
@martialgallorini sorry this took a while to get to, you were right, the font was missing! I've made an example for iOS, its in the master branch, let me know if you have any other issues.
