### ISSUE TITLE
ofxUIButton Release function hit variable must be updated at proper moment

### ISSUE THREAD

**Issue by ChulseungYoo** [rezaali/ofxUI#247]
in ofxUIButton::mouseReleased()
hit variable is updated at end of function.
it normally does not make problem. but when calling some functions that blocks, it has some bug.
I called ofSystemLoadDialog(..., folder=true)

and it blocks while user select a folder, and when mouse moves to outside of the button, it's hit variable is still true, therefore mouseReleased() function is called again,

**Comment by ChulseungYoo** [comment]
hit =  false have to moved to 
    if(rect->inside(x, y) || (label->isVisible() && label->getPaddingRect()->inside(x, y)))
    {
        hit = true;
like mousePressed()

**Comment by ChulseungYoo** [comment]
like ofxUIButton::mousePressed() 
hit = false; should positioned here.

    if(rect->inside(x, y) || (label->isVisible() && label->getPaddingRect()->inside(x, y)))
    {
        hit = false;

**Comment by rezaali** [comment]
updated here https://github.com/rezaali/ofxUI/commit/122dfe4735fa0908ac42ffcf9fdfec867871b462, thanks!
