### ISSUE TITLE
ofxUICanvas::setVisible crashes in latest build

### ISSUE THREAD

**Issue by genekogan** [rezaali/ofxUI#250]
I'm getting runtime errors when toggling visibility of a canvas -- only in the most recent nightly builds, not in 0.8.4. So presuming it may be an issue for 0.9.

    void ofApp::setup(){
        gui = new ofxUICanvas("hello");
    }
    void ofApp::update(){
    }
    void ofApp::draw(){
    }
    void ofApp::keyPressed(int key){
        if (key=='1') {
            gui->toggleVisible();
        }
    }

![screen shot 2015-06-26 at 5 06 14 pm](https://cloud.githubusercontent.com/assets/1335251/8387328/b450a820-1c25-11e5-993f-8c67406dd80d.png)

**Comment by rezaali** [comment]
thanks for letting me know, ofxUI needs a lot of love, will try to update it this weekend for OF 0.9

**Comment by genekogan** [comment]
awesome!
can i also alert you to this [issue](https://github.com/rezaali/ofxUI/issues/227) i opened some time ago which may be related?
ofxUI often crashes the app if you try to remove widgets on mouse clicks (usually because it attempts to access the `mouseReleased` function of a widget which was deleted while the mouseReleased iterator is still running.
this makes it difficult to regenerate canvases, which would be a very useful feature. this is the only major issue i often encounter when using it, otherwise it's very stable.

**Comment by rezaali** [comment]
@genekogan thanks! So the bug is fixed in the develop branch (working on updating the examples too), can you make another issue regarding the mouseReleased function / delete widget crash. 

Commit: 576bef80fb918241b335f7f0e9891d98ca7a6385

**Comment by genekogan** [comment]
awesome, thanks!
i already made that issue some time ago -- [it is here](https://github.com/rezaali/ofxUI/issues/227).
