### ISSUE TITLE
can't compile on 0.9.3 in raspberry pi 2 ARM

### ISSUE THREAD

**Issue by moebiussurfing** [rezaali/ofxUI#257]
i am getting this error in red:

```
/home/pi/of_v0.9.3_linuxarmv7l/addons/ofxUI/src/ofxUISortableList.cpp: In member function 'ofxUIDraggableLabelButton* ofxUISortableList::getActiveWidget(int, int)':
/home/pi/of_v0.9.3_linuxarmv7l/addons/ofxUI/src/ofxUISortableList.cpp:221:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < listItems.size(); i++)
```
                       ^
g++: internal compiler error: Killed (program cc1plus)

it continues compiling and finally stoped here:

```
/home/pi/of_v0.9.3_linuxarmv7l/addons/ofxUI/src/ofxUIOFWrapper.h:421:12: warning: 'int ofxUIGetWidth()' defined but not used [-Wunused-function]
 static int ofxUIGetWidth()
            ^
make[1]: Leaving directory '/home/pi/of_v0.9.3_linuxarmv7l/apps/baseCam360/baseCamRPI'
/home/pi/of_v0.9.3_linuxarmv7l/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:125: recipe for target 'Release' failed
make: *** [Release] Error 2
```

**Comment by rezaali** [comment]
well just off the top of my head, rpi is complaining that the type returned by listItems.size(); isn't an int and finally its complaining that ofxUIGetWidth() isn't used, so the compiler settings are pretty hardcore. You might want to try to easy up the compiler to accept these warnings. 

ofxUI was written in 2010 when I knew very little about programming, I'd recommending using something more modern and robust.

**Comment by jvcleave** [comment]
Your compiler is probably getting killed because you ran out of memory. If you are using `make -j4` be aware each job takes up memory.

**Comment by moebiussurfing** [comment]
thanks for the answers! 
yes @jvcleave !!, :) .I am getting memory errors. Some of the examples where compiling fine yesterday (like ofxGui's guiExample), now aren't. So how can I limit the memory usage? Must to not use the j4 for multicore use?

**Comment by jvcleave** [comment]
yeah - just use -j2 or a cross-compiler

**Comment by moebiussurfing** [comment]
Thanks a lot @jvcleave !! It worked after set -j2 to avoid the memory errors. I only needed to install the font: 'sudo pacman -S ttf-fira-sans'. You rescued me after some hours of losing time. BTW I started to check your ofxImGui. It seems the best way to get faster performance.
